name: ci

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mamadoudev/python-app:${{ env.COMMIT_SHORT_SHA }}