name: cicd

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**

jobs:
  Build_and_Push:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ env.sha_short }}
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mamadoudev/python-app:${{ env.sha_short }}

  deploy:
    runs-on: self-hosted
    needs: Build_and_Push
    steps:
      - uses: actions/checkout@v2
       
      - name: Modify the k8s deployment file
        shell: bash
        run: |
          echo ${{needs.Build_and_Push.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.Build_and_Push.outputs.commit_id}}"' charts/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'update image tag to ${{needs.Build_and_Push.outputs.commit_id}}'

      -
        name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app
