name: cicd

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**

jobs:
  Build_and_Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mamadoudev/python-app:${{ env.sha_short }}

  deploy:
    runs-on: self-hosted
    needs: Build_and_Push
    steps:
      - 
        name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
      - name: Login to ArgoCD
        run: |
          argocd login argocd-server.argocd.svc.cluster.local \
          --insecure \
          --grpc-web \
          --username admin \ 
          --password ${{ secrets.ARGOCD_PASSWORD }}
      - name: Sync Application
        run: |
          argocd app sync python-app
